import { createContext, useState, useEffect } from 'react';

export const LanguageContext = createContext();

const translations = {
  uz: {
    tab_dashboard: "Boshqaruv paneli",
    tab_crops: "Ekinlar",
    tab_maps: "Xaritalar",
    tab_irrigation: "Sug'orish",
    tab_scanner: "Kasallik skaneri",
    tab_reports: "Hisobotlar",
    tab_ai: "AI tavsiyalar",
    tab_notifications: "Bildirishnomalar",
    tab_settings: "Sozlamalar",
    logout: "Chiqish",
    sub_dashboard: "Umumiy holat",
    sub_crops: "Ekinlar ro'yxati",
    sub_maps: "Maydonlar xaritasi",
    sub_irrigation: "Suv monitoringi",
    sub_scanner: "AI kasallik tahlili",
    sub_reports: "Hisobot va statistika",
    sub_ai: "Sun'iy intellekt",
    sub_notifications: "Xabarnomalar",
    sub_settings: "Tizim sozlamalari",
    obuna_rejasi: "Obuna rejasi",
    premium: "Premium",
    obuna_exp: "2025-12-31 gacha amal qiladi",
    rejani_yangilash: "Rejani yangilash",
    tashkent_uzb: "Toshkent, O'zbekiston",
    partly_cloudy: "Qisman bulutli",
    welcome: "Xush kelibsiz",
    today_xo: "Bugun xo'jaligingiz juda yaxshi holatda. Davom eting!",
    search_placeholder: "Qidirish...",
    update_data: "Ma'lumotlarni yangilash",
    kpi_crop_health: "Ekinlar sog'lig'i",
    kpi_water_reserve: "Suv zaxirasi",
    kpi_pest_risk: "Kasallik xavfi",
    kpi_yield_forecast: "Hosildorlik prognozi",
    kpi_total_revenue: "Umumiy daromad",
    status_juda_yaxshi: "Juda yaxshi",
    status_yaxshi: "Yaxshi",
    status_past: "Past",
    status_yuqori: "Yuqori",
    status_bu_oy: "Bu oy",
    fields_map_title: "Maydonlar xaritasi",
    legend_excellent: "A'lo",
    legend_good: "Yaxshi",
    legend_average: "O'rta",
    legend_poor: "Past",
    all_fields: "Barcha maydonlar",
    jami_maydon: "Jami maydon",
    crop_types: "Ekin turlari",
    active_fields: "Faol maydonlar",
    open_full_map: "To'liq xaritada ochish",
    ai_recom_title: "Bugungi kun uchun 3 ta asosiy tavsiya",
    ai_recom_sub: "AI sizning maydonlaringizni tahlil qildi",
    ai_rec_1_title: "Sug'orish kerak emas",
    ai_rec_1_desc: "Namlik darajasi optimal (65%)",
    ai_rec_2_title: "Kasallik xavfi past",
    ai_rec_2_desc: "Bakterial kuyish aniqlanmadi",
    ai_rec_3_title: "O'g'itlash tavsiya etiladi",
    ai_rec_3_desc: "Azot o'g'itini 3 kundan keyin bering",
    view_all_advices: "Barcha tavsiyalarni ko'rish",
    moisture_level: "Namlik darajasi",
    weekly: "Haftalik",
    weather_forecast: "Ob-havo prognozi",
    seven_days: "7 kunlik",
    humidity: "Namlik",
    wind: "Shamol",
    precipitation: "Yog'ingarchilik",
    recent_activities: "So'nggi faoliyatlar",
    view_all: "Barchasi",
    today: "Bugun",
    tuesday: "Sesh",
    wednesday: "Chor",
    thursday: "Pay",
    friday: "Jum",
    saturday: "Shan",
    sunday: "Yak",
    confirm_logout: "Tizimdan chiqmoqchimisiz?",
    quick_actions: "Tezkor amallar",
    close: "Yopish",
    add_field: "Maydon qo'shish",
    scan_leaf: "Barg skanerlash",
    ask_ai: "AI agronomdan so'rash"
  },
  en: {
    tab_dashboard: "Dashboard",
    tab_crops: "Crops",
    tab_maps: "Maps",
    tab_irrigation: "Irrigation",
    tab_scanner: "Disease Scanner",
    tab_reports: "Reports",
    tab_ai: "AI Insights",
    tab_notifications: "Notifications",
    tab_settings: "Settings",
    logout: "Logout",
    sub_dashboard: "Overview",
    sub_crops: "Crops List",
    sub_maps: "Fields Map",
    sub_irrigation: "Water Monitoring",
    sub_scanner: "AI Disease Analysis",
    sub_reports: "Reports & Stats",
    sub_ai: "Artificial Intelligence",
    sub_notifications: "Alert Logs",
    sub_settings: "System Settings",
    obuna_rejasi: "Subscription Plan",
    premium: "Premium",
    obuna_exp: "Valid until 2025-12-31",
    rejani_yangilash: "Renew Plan",
    tashkent_uzb: "Tashkent, Uzbekistan",
    partly_cloudy: "Partly Cloudy",
    welcome: "Welcome",
    today_xo: "Your farm is in great condition today. Keep it up!",
    search_placeholder: "Search...",
    update_data: "Update Data",
    kpi_crop_health: "Crop Health",
    kpi_water_reserve: "Water Reserve",
    kpi_pest_risk: "Disease Risk",
    kpi_yield_forecast: "Yield Forecast",
    kpi_total_revenue: "Total Revenue",
    status_juda_yaxshi: "Very Good",
    status_yaxshi: "Good",
    status_past: "Low",
    status_yuqori: "High",
    status_bu_oy: "This Month",
    fields_map_title: "Fields Map",
    legend_excellent: "Excellent",
    legend_good: "Good",
    legend_average: "Average",
    legend_poor: "Poor",
    all_fields: "All Fields",
    jami_maydon: "Total Area",
    crop_types: "Crop Types",
    active_fields: "Active Fields",
    open_full_map: "Open Full Map",
    ai_recom_title: "3 Core Recommendations for Today",
    ai_recom_sub: "AI has analyzed your fields",
    ai_rec_1_title: "Watering not required",
    ai_rec_1_desc: "Moisture level is optimal (65%)",
    ai_rec_2_title: "Disease risk is low",
    ai_rec_2_desc: "Bacterial blight not detected",
    ai_rec_3_title: "Fertilization recommended",
    ai_rec_3_desc: "Apply nitrogen fertilizer in 3 days",
    view_all_advices: "View All Advices",
    moisture_level: "Moisture Level",
    weekly: "Weekly",
    weather_forecast: "Weather Forecast",
    seven_days: "7 Days",
    humidity: "Humidity",
    wind: "Wind",
    precipitation: "Precipitation",
    recent_activities: "Recent Activities",
    view_all: "View All",
    today: "Today",
    tuesday: "Tue",
    wednesday: "Wed",
    thursday: "Thu",
    friday: "Fri",
    saturday: "Sat",
    sunday: "Sun",
    confirm_logout: "Are you sure you want to logout?",
    quick_actions: "Quick Actions",
    close: "Close",
    add_field: "Register Field",
    scan_leaf: "Scan Leaf Disease",
    ask_ai: "Ask AI Agronomist"
  },
  ru: {
    tab_dashboard: "Панель управления",
    tab_crops: "Культуры",
    tab_maps: "Карты",
    tab_irrigation: "Орошение",
    tab_scanner: "Сканер болезней",
    tab_reports: "Отчеты",
    tab_ai: "AI Рекомендации",
    tab_notifications: "Уведомления",
    tab_settings: "Настройки",
    logout: "Выйти",
    sub_dashboard: "Общий статус",
    sub_crops: "Список культур",
    sub_maps: "Карта полей",
    sub_irrigation: "Мониторинг воды",
    sub_scanner: "AI анализ болезней",
    sub_reports: "Отчеты и статистика",
    sub_ai: "Искусственный интеллект",
    sub_notifications: "Лог алертов",
    sub_settings: "Настройки системы",
    obuna_rejasi: "План подписки",
    premium: "Премиум",
    obuna_exp: "Действителен до 2025-12-31",
    rejani_yangilash: "Обновить план",
    tashkent_uzb: "Ташкент, Узбекистан",
    partly_cloudy: "Переменная облачность",
    welcome: "Добро пожаловать",
    today_xo: "Сегодня ваше хозяйство в отличном состоянии. Так держать!",
    search_placeholder: "Поиск...",
    update_data: "Обновить данные",
    kpi_crop_health: "Здоровье культур",
    kpi_water_reserve: "Запасы воды",
    kpi_pest_risk: "Риск болезней",
    kpi_yield_forecast: "Прогноз урожайности",
    kpi_total_revenue: "Общий доход",
    status_juda_yaxshi: "Очень хорошо",
    status_yaxshi: "Хорошо",
    status_past: "Низкий",
    status_yuqori: "Высокий",
    status_bu_oy: "В этом месяце",
    fields_map_title: "Карта полей",
    legend_excellent: "Отлично",
    legend_good: "Хорошо",
    legend_average: "Средне",
    legend_poor: "Плохо",
    all_fields: "Все поля",
    jami_maydon: "Общая площадь",
    crop_types: "Виды культур",
    active_fields: "Активные поля",
    open_full_map: "Открыть во всю карту",
    ai_recom_title: "3 основные рекомендации на сегодня",
    ai_recom_sub: "ИИ проанализировал ваши поля",
    ai_rec_1_title: "Полив не требуется",
    ai_rec_1_desc: "Уровень влажности оптимален (65%)",
    ai_rec_2_title: "Риск болезней низкий",
    ai_rec_2_desc: "Бактериальный ожог не обнаружен",
    ai_rec_3_title: "Рекомендуется удобрение",
    ai_rec_3_desc: "Внесите азотное удобрение через 3 дня",
    view_all_advices: "Посмотреть все рекомендации",
    moisture_level: "Уровень влажности",
    weekly: "Еженедельно",
    weather_forecast: "Прогноз погоды",
    seven_days: "7 дней",
    humidity: "Влажность",
    wind: "Ветер",
    precipitation: "Осадки",
    recent_activities: "Последние действия",
    view_all: "Все",
    today: "Сегодня",
    tuesday: "Вторник",
    wednesday: "Среда",
    thursday: "Четверг",
    friday: "Пятница",
    saturday: "Суббота",
    sunday: "Воскресенье",
    confirm_logout: "Вы уверены, что хотите выйти?",
    quick_actions: "Быстрые действия",
    close: "Закрыть",
    add_field: "Добавить поле",
    scan_leaf: "Сканировать лист",
    ask_ai: "Спросить AI агронома"
  }
};

export function LanguageProvider({ children }) {
  const [currentLanguage, setCurrentLanguage] = useState(() => {
    return localStorage.getItem('language') || 'uz';
  });

  useEffect(() => {
    localStorage.setItem('language', currentLanguage);
  }, [currentLanguage]);

  const changeLanguage = (lang) => {
    if (translations[lang]) {
      setCurrentLanguage(lang);
    }
  };

  const t = (key) => {
    return translations[currentLanguage]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}
